<tr class="rule"><td colspan="3"></td></tr> 
<tr class="space"><td colspan="3" ></td></tr>
<tr> <td valign="top">

<div id="nav-links"> 

<ul>
<li><a href="index.php", title="Tony's web home">Home page</a></li>
<li><a href="larxxia.php" title="textbook developing Linear
Algebra for the 21st century">Linear Algebra for 21st
C</a></li>
<li><a href="eqnfreetool.php" title="equation-free function
toolbox for Matlab and Octave">Equation-Free
Toolbox</a></li>
<li><a href="modelling.php" title="create your own book on
the rational modelling of emergent dynamics in complex
systems">Modelling emergence book</a></li>
<li><a href="ecfm.php", title="Elementary calculus of
financial mathematics">Financial math book</a></li>
<li><a href="LaTeX/index.html", title="Introduction to why
LaTeX, Contents, and other info sources">best LaTeX
introduction</a></li>
<li><a href="<?php echo $servaddr;?>holistic1.php" 
title="submit a PDE to find its holistic discretisation"
>Holistic discretisation 1</a></li>
<li><a href="<?php echo $servaddr;?>holistic3.php" 
title="submit your three coupled PDEs to find their holistic discretisation"
>Holistic discretisation 3</a></li>
<!--<li><a href="<?php echo $servaddr;?>sdenf.php" title="submit
your slow/fast deterministic or stochastic DE to find its
normal form">SDE normal form</a></li>
-->
<li><a href="<?php echo $servaddr;?>sdenf.php" title="submit
your slow/fast deterministic or stochastic DE to find its
slow, stable, unstable, or combination manifolds, and a
normal form evolution thereon">SDE slow manifold et
al.</a></li>
<li><a href="<?php echo $servaddr;?>gencm.php" title="submit
your autonomous system of ODEs to find any invariant
manifold and evolution thereon, including slow, centre,
spectral submanifolds, nonlinear normal modes">Construct
invariant manifolds</a></li>
<!--<li><a href="multifractal.php" title="submit 2D data to explore fractality">Multifractal analyser</a></li>
-->
<li><a href="legofractals.php" title="lego fractals for you
to construct">Lego Fractals</a></li>
<li><a href="software.php" title="Some miscellaneous
software contributions">Some software</a></li>
<li><a href="publications.php" title="list of most of my
research publications">Research publications</a></li>
<li><a href="http://www.amazon.co.uk/-/e/B08DQJZMWW"
title="Amazon's A. J. Roberts page">Amazon's Author
Page</a></li>
<li class="title"><em>Other homes</em> <ul>
<li><a href="http://www.maths.adelaide.edu.au",
title="School of Mathematical Sciences web
home">Mathematical Sciences</a></li>
<li><a href="http://ecms.adelaide.edu.au/", title="Faculty
of Engineering, Computing and Mathematical Sciences web
home">Faculty ECMS</a></li>
<li><a href="http://www.adelaide.edu.au", title="The
university's web home">University of Adelaide</a></li> </ul>
<?php // Add more links in the space below here?>

</ul>
<div id="google_translate_element"></div><script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
}
</script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style ">
<a class="addthis_button_preferred_1"></a>
<a class="addthis_button_preferred_2"></a>
<a class="addthis_button_preferred_3"></a>
<a class="addthis_button_preferred_4"></a>
<a class="addthis_button_compact"></a>
<a class="addthis_counter addthis_bubble_style"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4e6929665596e5d6"></script>
<!-- AddThis Button END -->

<?php if(isset ($thanks)) echo $thanks;?>


<form name="afm_form_791186e1" id="afm_form_791186e1" action="http://free.allforms.mailjol.net/u/791186e1.php" method="POST" style="margin: 0px">
<table border="0" cellpadding="1" cellspacing="0" style="text-align: left; border: 2px solid #006622; border-collapse: collapse" width="1%" bgcolor="#F0F0F0"><tr>
<td  bgcolor="#006622" style="color: #FFFFFF; font-weight: bold; padding: 2px">Contact me</td>
</tr><tr>
<td  style="padding: 2px; font-size: small; color: #000000">Questions marked by * are required.</td>
</tr><tr>
<td style="font-size: small; font-weight: bold;  padding-right: 2px; color: #000000">Name: *<br><input type="Text" name="Name:" size="20" style="font-size: 11px; font-family: Verdana"></td>
</tr><tr>
<td  style="font-size: small; font-weight: bold;  padding-right: 2px; color: #000000">Email: *<br><input type="Text" name="Email:" size="20" style="font-size: 11px; font-family: Verdana"></td>
</tr><tr>
<td  style="font-size: small; font-weight: bold;  padding-right: 2px; color: #000000">Message:<br><textarea rows="4" cols="20" style="font-size: 11px; font-family: Verdana" name="Message:"></textarea></td>
</tr><tr>
<td align="center" style="padding: 4px"><input type="submit" name="submit" value="Submit" style="font-size: 11px; font-family: Verdana"> &nbsp;<input type="reset" name="reset" value="Reset" style="font-size: 11px; font-family: Verdana"></td>
</tr>
</table></form>


</div> </td>

<td colspan="2"><div id="content">
